- name: install dependency packages
  apt:  name={{item}} state=present update_cache=yes
  sudo: yes
  with_items:
    - unzip

- name: get package
  get_url: url=https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip dest=/opt/
  sudo: yes

- name: unzip package
  command: unzip 0.5.0_linux_amd64.zip -d /usr/local/bin/
           chdir=/opt creates=/usr/local/bin/consul
  sudo: yes

- name: Allow execute binary
  file:
    path: /usr/local/bin/consul
    mode: 755
  sudo: yes
