- name: install dependency packages
  apt:  name={{item}} state=present update_cache=yes
  sudo: yes
  with_items:
    - unzip

- name: get package
  get_url: url=https://dl.bintray.com/mitchellh/consul/0.5.0_linux_amd64.zip dest=/opt/
  sudo: yes

- name: unzip package
  command: unzip 0.5.0_linux_amd64.zip -d /usr/local/bin/
           chdir=/opt creates=/usr/local/bin/consul
  sudo: yes

- name: Allow execute binary
  file:
    path: /usr/local/bin/consul
    mode: 755
  sudo: yes

- name: Create consul directory
  file:
    path: /etc/consul
    state: directory
  sudo: yes

- name: Put Consul config
  template:
    src: config.json.j2
    dest: /etc/consul/config.json
  sudo: yes

- name: Put Consul script
  copy:
    src: consul
    dest: /etc/init.d/consul
    mode: 0755
  sudo: yes

- name: Start consul service
  service:
    name: consul
    state: started
    enabled: yes
  sudo: yes

